export {Home} from './Home'
export {Login} from './Login'
export {Registration} from './Registration'
export {FullPost} from './FullPost'
export {AddPost} from './AddPost'
export {TagPosts} from './TagPosts'
export {NotFound} from './NotFound'